name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        # Specify the repository you want to clone
        run: |
          git clone https://gitlab.com/cloud-devops-assignments/spring-boot-react-example.git
          cd spring-boot-react-example
          # Perform actions on the cloned repo
          echo "Cloned public repo successfully!"


      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'  # Options: 'zulu', 'adopt', 'temurin', etc.
          java-version: '11'

      - name: Build with Maven
        run: ./mvnw clean package

      - name: Run unit tests
        run: ./mvnw test

  dockerize:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_REGISTRY }}/spring-backend:${{ github.sha }} .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/spring-backend:${{ github.sha }}

  deploy:
    needs: dockerize
    runs-on: ubuntu-latest

    steps:
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment-backend.yaml
